# Generated by Django 6.0.6 on 2026-06-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0002_rename_date_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
